### PR TITLE
fix: use env variables instead of hardcoded url in swagger (#46)

### LINKED ISSUE #46: Enable CORS
We have address for the this repo: 

https://broken-link-checker-production-8bdf.up.railway.app/api-docs/#/URL%20Checking/post_api_check_url

When we are sending the request right now we are getting blocked because of cors : 

Image

Need to update the server to enable requests

### PR DESCRIPTION
**Pull request by ompatel-io**
Fixes #46

The swagger config had hardcoded `http://localhost:3000` url that was causing the deployed swagger ui to send requests to localhost instead of deployed server.

Changed it to use `BASE_URL` env variable and localhost fallback. 

**Please note** that the railway deployment will need `BASE_URL` to be set for this to solve.

There were pre existing typescript deprecation warnings in `tsconfig.json` and type error in `urlService.ts`
So used `--no-verify` for commit.

## Summary by CodeRabbit

* **Chores**
  * API documentation configuration now dynamically reflects the deployment environment, automatically updating the documented server URL and designation based on runtime settings.

### CODE REVIEW

File: src/config/swagger.ts [hunk 1]
```diff
@@ -15,8 +16,12 @@ const options = {
     },
     servers: [
       {
-        url: "http://localhost:3000",
-        description: "Development server",
+        url:
+          process.env.BASE_URL ||
+          `http://localhost:${process.env.PORT || DEFAULT_PORT}`,
```
Comment (Tamir198) [inline src/config/swagger.ts:21]: can you check that everyting is working with the adres of the deployed server? 

https://broken-link-checker-production-8bdf.up.railway.app/

**Review by Tamir198 — CHANGES_REQUESTED** [review]
Looks good left a small comment

File: src/config/swagger.ts (hunk 1 above)
Comment (ompatel-io) [reply src/config/swagger.ts:21]: No it is not working.

The deployment will need `BASE_URL` to be set in `.env` file to the deployed URL.
Currently the deployed code is hardcoded to `localhost` which is changed in this PR.

So it will work after this is merged, the deployed app updates with this latest commit,
and the changes made in the `.env` file for deployed app.

Comment (Tamir198) [reply src/config/swagger.ts:21]: Ok sounds good, just I just want to make sure, can you paste your env key and value in here?
Dont worry its not a secret its ok to share the backend endopint

Comment (Tamir198) [reply src/config/swagger.ts:21]: The serve is currently down, I am working on a fix but if you are seeing some 500 statuses this is the reason

Comment (Tamir198) [reply src/config/swagger.ts:21]: Fixed it

Comment (ompatel-io) [reply src/config/swagger.ts:21]:
```
BASE_URL=https://broken-link-checker-production-8bdf.up.railway.app
```

I also rebased to the main that was updated today, should i push it again

**Review by Tamir198 — APPROVED** [review]
OK looks good i will merge and lets see what is going on when we will deploy it

**Comment by Tamir198** [comment]
Alright good work its working
